source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "jbuilder", "~> 2.13"
gem "bootsnap", require: false
gem "rack-cors"
gem "jwt", "~> 3.2"
gem "faraday", "~> 2.14"
gem "dotenv-rails", "~> 3.2"
gem "discard", "~> 2.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
